endpoint:
  port: 2003
  multicore: true
  reuseport: true
bus:
  queued: false
index:
  driver: opensearch
  addresses: 
    - https://localhost:9200
  name: goshenite
  username: admin
  password: admin
  insecure: true
  region: eu-central-1
  sigv4: false
  flush:
    bytes: 10_000_000  # items
    interval: 5s
  cache:
    size: 2560  # in MB
store:
  driver: devnull
  retention: 336h  # 2 weeks
  resolution: 60s
  hosts: ['localhost']
  port: 9042
  keyspace: goshenite
  username: cassandra
  password: cassandra
  table: metrics
general:
  level: debug
  profiler: false
stats:
  path: 'goshenite.interal'
  interval: 60s
  log: true
  segment: 1
