endpoint:
  port: 2003
  multicore: true
  reuseport: true
index:
  driver: opensearch
  addresses: 
    - https://localhost:9200
  name: goshenite
  username: admin
  password: admin
  insecure: true
  region: eu-central-1
  sigv4: false
  flush:
    bytes: 10485760  # 10 MB
    interval: 5s
  cache:
    shards: 1024
    lifewindow: 30m
    cleanwindow: 5m
    size: 2684354560  # 2.5GB
store:
  driver: devnull
  retention: 336h  # 2 weeks
  resolution: 60s
  hosts: ['localhost']
  port: 9042
  keyspace: goshenite
  username: cassandra
  password: cassandra
  table: metrics
logging:
  level: debug
stats:
  path: 'goshenite.interal'
  interval: 60s
  log: true
  segment: 1
